import React, { useState, useEffect } from "react";
import { Button, Input, Textarea } from "@windmill/react-ui";
import { useTranslation } from "react-i18next";
import { FiX } from "react-icons/fi";

//internal import
import Uploader from "@/components/image-uploader/Uploader";
import Error from "@/components/form/others/Error";
import useUtilsFunction from "@/hooks/useUtilsFunction";

const VariantEditDrawer = ({
  variant,
  onSave,
  onClose,
  language,
  errors,
  variantTitle,
}) => {
  const { t } = useTranslation();
  const { showingTranslateValue, getNumber, getNumberTwo } = useUtilsFunction();
  const [variantImages, setVariantImages] = useState(variant?.image || []);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(false);
  const [currentSku, setCurrentSku] = useState(variant?.sku || "");
  const [currentBarcode, setCurrentBarcode] = useState(variant?.barcode || "");
  const [currentDescription, setCurrentDescription] = useState(
    variant?.description?.[language] || ""
  );
  const [currentHighlights, setCurrentHighlights] = useState(
    variant?.highlights?.[language] || ""
  );
  const [currentSlug, setCurrentSlug] = useState(variant?.slug || "");
  const [currentTitle, setCurrentTitle] = useState(
    variant?.title?.[language] || ""
  );
  const [currentPrice, setCurrentPrice] = useState(variant?.price || 0);
  const [currentOriginalPrice, setCurrentOriginalPrice] = useState(variant?.originalPrice || 0);
  const [currentQuantity, setCurrentQuantity] = useState(variant?.quantity || 0);

  // Update local state when variant changes
  useEffect(() => {
    if (variant) {
      setCurrentSku(variant?.sku || "");
      setCurrentBarcode(variant?.barcode || "");
      setCurrentDescription(variant?.description?.[language] || "");
      setCurrentHighlights(variant?.highlights?.[language] || "");
      setCurrentSlug(variant?.slug || "");
      setCurrentTitle(variant?.title?.[language] || "");
      setVariantImages(variant?.image || []);
      setCurrentPrice(variant?.price || 0);
      setCurrentOriginalPrice(variant?.originalPrice || 0);
      setCurrentQuantity(variant?.quantity || 0);
    }
  }, [variant, language]);

  // Auto-generate title from combination attributes if title is empty
  const generateTitleFromAttributes = () => {
    if (!variant || !variantTitle) return "";

    // Use variantTitle to get actual attribute names instead of IDs (same logic as table)
    const attributeNames = variantTitle
      ?.map((att) => {
        const attributeData = att?.variants?.filter(
          (val) => val?.name !== "All"
        );

        const attributeName = attributeData?.find(
          (v) => v._id === variant[att?._id]
        )?.name;

        if (attributeName === undefined) {
          return attributeName?.en;
        } else {
          return showingTranslateValue(attributeName);
        }
      })
      ?.filter(Boolean)
      .join(" ");

    return attributeNames || "";
  };

  // Generate initial slug when drawer opens
  useEffect(() => {
    if (variant) {
      // Auto-generate title if it's empty
      if (!variant.title?.[language] || !variant.title[language].trim()) {
        const autoTitle = generateTitleFromAttributes();
        if (autoTitle) {
          setCurrentTitle(autoTitle);
          // Also generate slug for the auto-generated title
          handleSlugGeneration(autoTitle);
          setIsSlugAutoGenerated(true);
        }
      } else if (variant.title?.[language]) {
        // If variant has a title but no slug, generate slug
        setCurrentTitle(variant.title[language]);
        if (!variant.slug) {
          handleSlugGeneration(variant.title[language]);
          setIsSlugAutoGenerated(true);
        } else {
          // If variant has both title and slug, set them
          setCurrentSlug(variant.slug);
          setIsSlugAutoGenerated(false);
        }
      }
    }
  }, [variant, language]);

  const handleSave = () => {
    const updatedVariant = {
      ...variant,
      title: {
        ...variant?.title,
        [language]: currentTitle,
      },
      sku: currentSku,
      barcode: currentBarcode,
      description: {
        ...variant?.description,
        [language]: currentDescription,
      },
      highlights: {
        ...variant?.highlights,
        [language]: currentHighlights,
      },
      slug: currentSlug,
      image: variantImages,
      price: getNumber(currentPrice),
      originalPrice: getNumberTwo(currentOriginalPrice),
      quantity: Number(currentQuantity),
    };
    onSave(updatedVariant);
  };

  const handleSlugGeneration = (title) => {
    if (!title) return;

    // Convert to lowercase, replace spaces and special characters with hyphens, remove multiple hyphens
    const slug = title
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, "") // Remove special characters except spaces and hyphens
      .replace(/\s+/g, "-") // Replace spaces with hyphens
      .replace(/-+/g, "-") // Replace multiple hyphens with single hyphen
      .replace(/^-|-$/g, ""); // Remove leading and trailing hyphens

    setCurrentSlug(slug);
    setIsSlugAutoGenerated(true);
  };

  const handleTitleChange = (e) => {
    const title = e.target.value;
    setCurrentTitle(title);

    // Auto-generate slug immediately as user types
    if (title && title.trim()) {
      // Small delay to prevent too many rapid updates
      setTimeout(() => {
        handleSlugGeneration(title);
      }, 100);
    } else {
      // Clear slug if title is empty
      setCurrentSlug("");
      setIsSlugAutoGenerated(false);
    }
  };

  const handleSlugChange = (e) => {
    const slug = e.target.value;
    // Ensure slug format is correct
    const formattedSlug = slug
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");

    setCurrentSlug(formattedSlug);
    setIsSlugAutoGenerated(false); // User is manually editing
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center">
      <div
        key={variant?._id || variant?.productId || "default"}
        className="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto"
      >
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            {t("EditVariant")}
          </h3>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
          >
            <FiX className="text-xl" />
          </button>
        </div>

        <div className="space-y-6">
          {/* Title */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantTitle")}
            </label>
            <Input
              name="variantTitle"
              type="text"
              placeholder={t("VariantTitle")}
              value={currentTitle}
              onChange={handleTitleChange}
              className=""
              required
            />
            <Error errorName={errors.variantTitle} />
          </div>

          {/* SKU */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantSKU")}
            </label>
            <Input
              name="variantSku"
              type="text"
              placeholder={t("VariantSKU")}
              value={currentSku}
              onChange={(e) => setCurrentSku(e.target.value)}
            />
            <Error errorName={errors.variantSku} />
          </div>

          {/* Barcode */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantBarcode")}
            </label>
            <Input
              name="variantBarcode"
              type="text"
              placeholder={t("VariantBarcode")}
              value={currentBarcode}
              onChange={(e) => setCurrentBarcode(e.target.value)}
            />
            <Error errorName={errors.variantBarcode} />
          </div>

          {/* Price Fields */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t("OriginalPrice")}
              </label>
              <Input
                name="variantOriginalPrice"
                type="number"
                placeholder={t("OriginalPrice")}
                value={currentOriginalPrice}
                onChange={(e) => setCurrentOriginalPrice(e.target.value)}
                min="0"
                step="0.01"
                onKeyDown={(e) => (e.key === '-' || e.key === 'e') && e.preventDefault()}
              />
              <Error errorName={errors.variantOriginalPrice} />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t("SalePrice")}
              </label>
              <Input
                name="variantPrice"
                type="number"
                placeholder={t("SalePrice")}
                value={currentPrice}
                onChange={(e) => setCurrentPrice(e.target.value)}
                min="0"
                step="0.01"
                onKeyDown={(e) => (e.key === '-' || e.key === 'e') && e.preventDefault()}
              />
              <Error errorName={errors.variantPrice} />
            </div>
          </div>

          {/* Quantity */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("Quantity")}
            </label>
            <Input
              name="variantQuantity"
              type="number"
              placeholder={t("Quantity")}
              value={currentQuantity}
              onChange={(e) => setCurrentQuantity(e.target.value)}
              min="0"
              onKeyDown={(e) => (e.key === '-' || e.key === 'e' || e.key === '.') && e.preventDefault()}
            />
            <Error errorName={errors.variantQuantity} />
          </div>

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantDescription")}
            </label>
            <Textarea
              name="variantDescription"
              placeholder={t("VariantDescription")}
              rows="4"
              value={currentDescription}
              onChange={(e) => setCurrentDescription(e.target.value)}
            />
            <Error errorName={errors.variantDescription} />
          </div>

          {/* Highlights */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantHighlights")}
            </label>
            <Textarea
              name="variantHighlights"
              placeholder={t("VariantHighlights")}
              rows="4"
              value={currentHighlights}
              onChange={(e) => setCurrentHighlights(e.target.value)}
            />
            <Error errorName={errors.variantHighlights} />
          </div>

          {/* Slug */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantSlug")}
              {isSlugAutoGenerated && (
                <span className="ml-2 text-xs text-green-600 font-normal">
                  (Auto-generated from title)
                </span>
              )}
            </label>
            <Input
              name="variantSlug"
              type="text"
              placeholder={t("VariantSlug")}
              value={currentSlug}
              onChange={handleSlugChange}
              className={
                isSlugAutoGenerated ? "border-green-300 bg-green-50" : ""
              }
              required
            />
            <p className="text-xs text-gray-500 mt-1">
              Slug will be automatically generated from the title. You can also
              edit it manually.
            </p>
            <Error errorName={errors.variantSlug} />
          </div>

          {/* Images */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t("VariantImages")}
            </label>
            <Uploader
              product
              folder="variant"
              imageUrl={variantImages}
              setImageUrl={setVariantImages}
            />
          </div>
        </div>

        <div className="flex justify-end space-x-3 mt-6">
          <Button layout="outline" onClick={onClose} className="px-4 py-2">
            {t("Cancel")}
          </Button>
          <Button
            onClick={handleSave}
            className="px-4 py-2 bg-green-600 hover:bg-green-700"
          >
            {t("SaveVariant")}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default VariantEditDrawer;
